language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PRE_INSTALL_HOOK="opam pin add --no-action -y idds https://github.com/netkat-lang/idds.git"
 matrix:
   - DISTRO=ubuntu OCAML_VERSION=4.08
